before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
before_install:
  - cd $GEM; export BUNDLE_GEMFILE="`pwd`/Gemfile"
script:
  - bundle exec rake test_app
  - bundle exec rake spec
rvm:
  - 1.9.3
  - 2.0.0
